dist: xenial
services:
  - xvfb

language: java

deploy:
  # deploy to Github
  provider: releases
  api_key:
    secure: IsFmoYjbuZun6p71J89Bl7eMXAhNO0iTBSbbHIKTRD4usIKUpBUpeyf51TLLMHkNlVz7E3550PI/VusUzwcFyUx3nZcoiQwoa+LSrYU4JcD97Sy00n3gJhg52kv/ecLwDz9jPR8AOXrnpBd6PZOu+O6LErmN7lZGIjXibHC0+z0QhLxHrDvCl8BZgKQ8/mo5IOadj3iPjJUq7w3MYHNiyOBT8fRFNXaVrAjZokQcOYK2f+H+as5yTyDXbrdX/wRDRGs7ym624jNObrSQiVju64dEutuH9nKn1mPPMfG3OMHOr55U5XIc5qiB5tLQKYzaUWw8BRvvHQ+RbbVw26WWaT/Le2tthj8k11rultwqq7PP2i0+2TDnawKoRSwyPEJU7lITrTxH1zW8jRTAPqqZ445UAyh4UueIlXGSxjntg+gewCFx3VMFMUH+3HUGJ1tJn8WNVixA3YJxLb+5QVTXLu3gTxHpf5EfIPpdQsVfW39fRNkNkXyIlxwoknbNiEAAXHrvZkuEFbh1gkt4eExOs0QcrTzdJfrtAlgTFeWxxBaeEkNrA35tViW0wyytjiT2mliShwc/j0QmC9j4eto4d0d5bn2e+Vv8ypuVJoro8kC1iilsf4FGgi+7I1SKvQwKQTVAGmjU3m2xpRcoAGSp/9zkMh3YtA+d7aEWaH8Q+1o=
  file_glob: true
  file: "./build/libs/jwebassembly-api-*.jar"
  skip_cleanup: true
  overwrite: true
  on:
    repo: i-net-software/JWebAssembly-API
    tags: true
